### ISSUE TITLE
[main branch] 'project 02/README.md' has some errors

### ISSUE THREAD

**Issue by bpires** [victorsgb/explorer#1]
Hey Victor,

I've noticed that the `explorer/project 02/README.md` file, on the `main` branch, has a minor syntax error.

There was probably an inclusion by mistake on lines 11-13 that interrupted the regular page flow:

```Markdown
<<<<<<< HEAD
🔗 **[See it online](https://victorsgb.github.io/explorer/tree/stage02/project_02/)**
=======
```

Also, there is some left-over code on line 15:

```Markdown
>>>>>>> stage02
```

See the problem below:

![image](https://user-images.githubusercontent.com/86871991/167170618-02e812c7-969d-4400-8453-59b4c0d263ad.png)

Hope this was helpful!

Cheers man, keep going! 🔥

**Comment by victorsgb** [comment]
Hey Rafael!

Thank you very much for your contact.
I introduced this bug by mistake when merging the main branch to get the most updated README.md for this project, but didn't resolve quite well the conflicts...

I really appreciate your contribution. Thanks!
